services:
  model:
    image: {{cookiecutter.docker_registry}}/{{cookiecutter.docker_repo_name}}:latest-gpu
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-all}
    volumes:
      - "./:${PROJECT_DIR:-/home/user/workspaces/projects/{{cookiecutter.project_slug}}}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/home/user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
